### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by joywebpro** [multicolor-rgb/EasyComments-for-Bludit-CMS#2]
problem with the Captcha!
No email when a comment is posted.
once activated and deactivated the plugin, the Forum on the site is still visible.
bludit 3.15

**Comment by multicolor-rgb** [comment]
ok, i working with that now. Soon comes new version. I will replace captcha to hcaptcha

**Comment by multicolor-rgb** [comment]
https://github.com/multicolor-rgb/EasyComments-for-Bludit-CMS/tree/3.0
