### ISSUE TITLE
No Action, Nothing works at least for me

### ISSUE THREAD

**Issue by soeren1337** [multicolor-rgb/EasyComments-for-Bludit-CMS#3]
For me the plugin does not work at all. I tried the original version and one translated to german. The Page reloads two times after submitting the captcha but then: nothing. No Comments waiting for approval, no comments waiting mailed to me. Simply nothing happens.
Bludit V3.16.1

**Comment by multicolor-rgb** [comment]
I am working with that

**Comment by multicolor-rgb** [comment]
https://github.com/multicolor-rgb/EasyComments-for-Bludit-CMS/tree/3.0 if you like my work, buy me coffe (link inside plugin):)
